
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'EF4CB5A18A03C4C9683C5DE5629893AE'
    
_lr_action_items = {'$end':([1,2,3,4,6,10,15,16,17,18,19,20,21,],[-11,-9,-10,0,-2,-11,-7,-1,-8,-3,-6,-4,-5,]),'RPAREN':([2,3,9,10,15,17,18,19,20,21,],[-9,-10,17,-11,-7,-8,-3,-6,-4,-5,]),'DIVIDE':([1,2,3,6,9,10,15,16,17,18,19,20,21,],[-11,-9,-10,12,12,-11,-7,12,-8,12,-6,12,-5,]),'FLOAT':([0,5,7,8,11,12,13,14,],[3,3,3,3,3,3,3,3,]),'NUMBER':([0,5,7,8,11,12,13,14,],[2,2,2,2,2,2,2,2,]),'EQUALS':([1,],[8,]),'PLUS':([1,2,3,6,9,10,15,16,17,18,19,20,21,],[-11,-9,-10,11,11,-11,-7,11,-8,-3,-6,-4,-5,]),'LPAREN':([0,5,7,8,11,12,13,14,],[5,5,5,5,5,5,5,5,]),'TIMES':([1,2,3,6,9,10,15,16,17,18,19,20,21,],[-11,-9,-10,14,14,-11,-7,14,-8,14,-6,14,-5,]),'MINUS':([0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,],[7,-11,-9,-10,7,13,7,7,13,-11,7,7,7,7,-7,13,-8,-3,-6,-4,-5,]),'NAME':([0,5,7,8,11,12,13,14,],[1,10,10,10,10,10,10,10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,7,8,11,12,13,14,],[6,9,15,16,18,19,20,21,]),'statement':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME EQUALS expression','statement',3,'p_statement_assign','tt.py~',67),
  ('statement -> expression','statement',1,'p_statement_expr','tt.py~',71),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','tt.py~',75),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','tt.py~',76),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','tt.py~',77),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','tt.py~',78),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','tt.py~',85),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','tt.py~',89),
  ('expression -> NUMBER','expression',1,'p_expression_number','tt.py~',93),
  ('expression -> FLOAT','expression',1,'p_expression_float','tt.py~',97),
  ('expression -> NAME','expression',1,'p_expression_name','tt.py~',101),
]
